language: python
python:
  - "3.6"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
# command to run tests
script:
  - pytest
  - black --check ctdproc/

# safelist
#branches:
#  only:
#  - master
#  - stable